config/routes.rb
Weddingram::Application.routes.draw do
  root :to => 'articles#index'
  match '/about' => 'articles#about', :as => :about, :via => :get
  match '/wordclouds' => 'articles#wordclouds', :as => :wordclouds, :via => :get
  match '/articles/ngram_calculator' => 'articles#ngram_calculator', :as => :ngram_calculator, :via => :get
  match '/articles/search' => 'articles#search', :as => :search, :via => :get
  match '/articles/random' => 'articles#random', :as => :random, :via => :get
  match '/articles/tagline' => 'articles#tagline', :as => :tagline, :via => :get
  
  # TO DO: route anything else to homepage?
end

app/models/article.rb
# encoding: utf-8

class Article < ActiveRecord::Base
  DEFAULT_COLUMNS_TO_INCLUDE = %w(id url title published_on year month day article_text stripped_text summary image_url is_wedding)
  MAX_NGRAM_SIZE = 5
  TOTAL_KEY = "ngram:totals"
  NGRAM_ALL_YEARS_KEY = "ngram:all_years"
  DEFAULT_IMAGE_URL = 'http://i.imgur.com/dlrddMw.gif'
  
  default_scope select(DEFAULT_COLUMNS_TO_INCLUDE).where(:is_wedding => true)
  
  def self.redis
    $redis
  end
  
  def self.all_years
    redis.zrange(NGRAM_ALL_YEARS_KEY, 0, 100).map(&:to_i)
    # (1981..2013).to_a
  end
  
  def self.sorted_set_key(year, n)
    [year, n].join(":")
  end
  
  def self.pretty_ngram_summary(year, n, options = {})
    key = sorted_set_key(year, n)
    raw = redis.zrevrange(key, options[:offset] || 0, (options[:limit] || 10) - 1, :with_scores => true)
    
    raw.each_slice(2){|ary| puts "#{ary[0]} => #{ary[1].to_i}"}
    nil
  end
  
  ALLOWED_MATH_OPERATORS = ["+", "/", "(", ")"]
  
  def self.get_terms_from_query_string(qry)
    regex = %r{[^[[:word:]]\s\-\&#{ALLOWED_MATH_OPERATORS.join('')}]}
    qry.split(",").map{|t| t.squish.gsub(regex, '')}.select(&:present?)
  end
  
  def self.from_redis(string)
    qry, smoothing = string.split("::")
    
    terms = get_terms_from_query_string(qry)
    smoothing = smoothing.to_i if smoothing.present?
    
    {:query => terms.join(", "), :smoothing => smoothing, :raw => qry}
  end
  
  def self.recommended_query_hsh
    from_redis(Article.redis.srandmember("recommended_searches") || "Yale, Harvard, Princeton::1")
  end
  
  def self.ngram_query(terms, opts = {})
    smoothing = opts[:smoothing] || 1
    case_sensitive = false
    
    preprocess_method = case_sensitive ? :to_s : :downcase
    
    terms_hsh = terms.inject(ActiveSupport::OrderedHash.new) do |hsh, term|
      key = term.dup
      hsh[key] = inner_query(term.send(preprocess_method), smoothing)
      hsh
    end
    
    {:terms => terms_hsh, :years => all_years, :smoothing => smoothing, :tagline => Tagline.random}
  end
  
  def self.equation_query(equation, smoothing)
    individual_terms = equation.split(%r{[#{ALLOWED_MATH_OPERATORS.join('')}]}).map(&:squish).uniq.select(&:present?)
    raise 'equation is too big!' if individual_terms.size > 10
    
    data_hsh = individual_terms.inject({}) do |hsh, t|
      hsh[t] = inner_query(t, smoothing)
      hsh
    end
    
    years = all_years
    output = []
    
    years.size.times do |ix|
      e = equation.dup
      data_hsh.keys.each do |t|
        e.gsub!(/\b#{t}\b/, data_hsh[t][ix].to_s)
      end
      
      raw_value = eval(e)
      
      output << (raw_value.infinite? ? nil : raw_value)
    end
    
    return output
  end
  
  def self.inner_query(term, smoothing)
    return equation_query(term, smoothing) if term.is_equation?
    
    term.squish!
    n = term.split(" ").size
    
    years = all_years
    
    counts_hsh, totals_hsh = {}, {}
    
    Article.redis.pipelined do
      years.each do |year|
        key = Article.sorted_set_key(year, n)
        
        counts_hsh[year] = Article.redis.zscore(key, term)
        totals_hsh[year] = Article.redis.zscore(Article::TOTAL_KEY, key)
      end
    end
    
    counts = counts_hsh.sort_by{|year, val| year}.map{|ary| ary[1].value.to_f}
    totals = totals_hsh.sort_by{|year, val| year}.map{|ary| ary[1].value.to_f}
    
    output = []
    number_of_years = years.size
    
    number_of_years.times do |ix|
      lower = [0, ix - smoothing].max
      upper = [number_of_years - 1, ix + smoothing].min
      output << counts[lower..upper].sum / totals[lower..upper].sum
    end
    
    output
  end
  
  def self.simple_search(terms, opts = {})
    limit = opts[:limit] || 3
    n = terms.size
    qry_text = ""
    
    terms.each_with_index do |t, ix|
      qry_text << "#{' OR' if ix > 0} stripped_text LIKE ?"
    end
    
    conditions = [qry_text] + terms.map{|t| "%#{t.downcase}%" }
    
    Article.where(conditions).
            order("random()").
            limit(limit)
  end
  
  def self.full_text_search(terms, opts = {})
    terms = terms.map(&:split_into_equation_components).flatten.uniq.select(&:present?)
    
    limit = opts[:limit] || 3
    n = terms.size
    
    ts_query_arg = ""
    exact_qry_text = ""
    
    terms.each_with_index do |t, ix|
      # what about searching with &
      ts_query_arg << "#{' |' if ix > 0} (#{t.split(' ').reject{|w| w == '&'}.join(' & ')})"
      exact_qry_text << "#{' OR' if ix > 0} stripped_text LIKE ?"
    end
    
    full_text_conditions = ["to_tsvector('english', article_text) @@ to_tsquery(?)", ts_query_arg]
    exact_conditions = [exact_qry_text] + terms.map{|t| "%#{t.downcase}%" }
    
    scope_without_exact = Article.unscoped.select("id").where(:is_wedding => true).
                        where(full_text_conditions).
                        limit(100)
                        
    inner_sql_without_exact = scope_without_exact.to_sql
    inner_sql_with_exact = scope_without_exact.where(exact_conditions).to_sql
    
    articles = Article.where("id IN (#{inner_sql_with_exact})").order("random()").limit(3)
    
    if articles.length == 0
      Article.where("id IN (#{inner_sql_without_exact})").order("random()").limit(3)
    else
      articles
    end
  end
  
  def thumbnail_image_url
    read_attribute('image_url').to_s.gsub(/\-(thumbLarge|superJumbo)\./, '-thumbStandard.')
  end
  
  def image_url
    thumbnail_image_url.presence || DEFAULT_IMAGE_URL
  end
  
  def canonical_url
    url.gsub(/\?.*$/, '')
  end
  
  def self.wordcloud_urls
    ["http://i.imgur.com/LXUpNTt.png",
     "http://i.imgur.com/SHXfsbP.png",
     "http://i.imgur.com/vCq59h4.png",
     "http://i.imgur.com/anlSlKv.png"]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
  
  def ngram_calculator
    raise 'xhr only' unless request.xhr?
    
    terms = get_terms_from_params
    smoothing_factor = params[:s].blank? ? 1 : params[:s].to_i
    
    hsh = if (err = determine_if_any_errors(terms, smoothing_factor)).present?
      { :error => err }
    else
      Article.ngram_query(terms, :smoothing => smoothing_factor)
    end
    
    hsh[:error] = "Something went wrong" if hsh.blank?
    
    render :json => hsh
  end
  
  def search
    raise 'xhr only' unless request.xhr?
    
    terms = get_terms_from_params
    raise 'invalid search terms' if determine_if_any_errors(terms).present?
    
    articles = Article.full_text_search(terms, :limit => 3)
    
    render :text => render_to_string(:partial => 'summaries', :locals => {:articles => articles})
  end
  
  def random
    render :json => Article.recommended_query_hsh
  end
  
  def tagline
    render :text => Tagline.random
  end
  
  private
  
  def get_terms_from_params
    Article.get_terms_from_query_string(params[:q])
  end
  
  def determine_if_any_errors(terms, smoothing_factor = 1)
    if terms.blank?
      "Enter something!"
    elsif terms.size > 8
      "You can't enter more than 8 things!"
    elsif terms.any?{|t| t.is_too_long_to_be_a_valid_query?}
      "Search phrases can't contain more than #{Article::MAX_NGRAM_SIZE} words!"
    elsif smoothing_factor < 0 || smoothing_factor > 5
      "Smoothing Factor must be between 0 and 5"
    end
  end
end

app/views/articles/_summaries.html.erb
<h4>
  A few articles matching at least one of your search terms:
  <span class="btn btn-small moreArticles"><i class="icon-refresh"></i> See more articles</span>
</h4>

<% articles.each do |article| %>
  <%= render 'summary', :article => article %>
<% end %>

app/views/articles/_summary.html.erb
<div class="articleSummary clearfix">
  <div class="image">
    <%= link_to( image_tag(article.image_url, :class => :thumb), article.canonical_url, :target => :_blank ) %>
  </div>
  
  <div class="details">
    <div class="title">
      <%= link_to article.title, article.canonical_url, :target => :_blank %>
    </div>
    
    <div class="date">
      <small><%= article.published_on.strftime('%b %-d, %Y') %></small>
    </div>
    
    <div class="content">
      <%= article.summary %>
    </div>
  </div>
</div>

app/views/articles/about.html.erb
<div class="span12">
  <div class="page-header">
    <h1>
      <a href="/" class="logo"><%= name_of_site %></a><br>
    </h1>
  </div>

  <div class="span9">
    <div id="faq">
      <a href="/" class="homeNav">Home</a>

      <dl>
        <dt class="first">What is this?</dt>
        <dd>Wedding Crunchers lets you measure the frequency of specific phrases in <a href="http://www.nytimes.com/pages/fashion/weddings/index.html" target="_blank"><i>New York Times</i> wedding announcements</a> since 1981. When you search for a phrase, Wedding Crunchers graphs how common that phrase has been over time. The project was heavily inspired by the <a href="http://books.google.com/ngrams" target="_blank">Google Books Ngram Viewer</a></dd>

        <dt>I love it! Where can I read more about it?</dt>
        <dd>There's a detailed writeup on <%= link_to "Genius", writeup_url, :target => "_blank" %></dd>

        <dt>How many articles are searched?</dt>
        <dd>About 60,000 wedding and engagement announcements from 1981 through today. Articles that are part of the <a href="http://topics.nytimes.com/topics/features/style/fashionandstyle/columns/vows/index.html" target="_blank">Vows column</a> are specifically excluded, because they are written in a very different style from the regular announcements</dd>

        <dt>What about punctuation and case sensitivity?</dt>
        <dd>Wedding Crunchers is <em>not</em> case sensitive. Most punctuation is stripped out for you automatically, so you don't have to worry about it. Ampersands (<code>&</code>) are not stripped out, so include them if you're looking for law firms!</dd>

        <dt>What does the y-axis mean exactly?</dt>
        <dd>The y-axis represents the frequency of each phrase, as a percentage of all phrases that contain the same number of words. For example, if you search for <code>from New York</code>, the graph shows the number of times those words appear in exact order, divided by the total number of 3 word phrases in all of the articles</dd>

        <dt>And what is "smoothing"?</dt>
        <dd>Smoothing is a way to take moving averages, which can help identify trends in noisy data. If you set smoothing to 1, it means that at each year, the value graphed is the average of that year and the 1 year before and after. In general smoothing 1 is a good default, sometimes for less common terms you might want to use smoothing 2, or if you want to see the raw data, then smoothing 0</dd>

        <dt>Any other cool features?</dt>
        <dd>Sure, if you want to get fancy, you can use <code>+</code> and <code>/</code> to build advanced searches. Check out some of the recommended searches for examples</dd>

        <dt>What's the deal with the word clouds?</dt>
        <dd>Each <a href="/wordclouds">word cloud</a> contains the phrases that were most common in announcements from a particular decade relative to the other decades</dd>
        
        <dt>Where can I learn more about ngrams?</dt>
        <dd><a href="http://en.wikipedia.org/wiki/N-gram" target="_blank">Wikipedia</a> and the <a href="http://books.google.com/ngrams/info" target="_blank">Google Books Ngram Viewer</a> are good places to start</dd>

        <dt>How can I contact you?</dt>
        <dd>weddingcrunchers@gmail.com</dd>
      </dl>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="span12">
  <div class="page-header">
    <h1>
      <a href="/" class="logo"><%= name_of_site %></a><br>
      
      <small id="tagline">
        I am my beloved's, and my beloved<span class="rotating keep"><%= Tagline.random %></span>
        <i class="icon-refresh refreshTagline"></i>
      </small>
    </h1>
    
    <div class="moreInfo">
      Read the full writeup on <%= link_to "Genius", writeup_url, :target => "_blank" %>
       | <%= link_to "About", "/about" %>
    </div>
  </div>
  
  <p>
    Enter some <span class="hasPopover comma-separated">comma-separated</span> phrases to search:
    <a id="randomSearch" href="/" tabindex="1">(or just show me a good search! <i class="icon-refresh"></i>)</a>
  </p>

  <div class="form-container">
    <%= form_tag ngram_calculator_path, :method => :get, :remote => true, :id => 'ngramForm' do %>
      <div class="searchQuery">
        <div class="input-append">
          <%= search_field_tag :q, params[:q], :maxlength => 10_000, :tabindex => 2, :class => "collapsed" %>
          <%= submit_tag "Search New York Times Weddings!", :id => "ngramSubmit", :class => "btn", :tabindex => 3 %>
        </div>
      </div>
      
      <div class="smoothingInput">
        <label for="s" class="smoothing">Smoothing <span class="hasPopover">(?)</span>:</label>
        <%= number_field_tag :s, params[:s] || 1, :min => 0, :max => 5, :tabindex => 4 %>
      </div>
      
      <div class="socialLinks">
        <span id="tweetButton"></span>
        <div class="fb-like" data-href="http://www.weddingcrunchers.com" data-width="90" data-layout="button_count" data-show-faces="false" data-send="false"></div>
        <span id="exportGraph" class="btn btn-mini"><i class="icon-download"></i>Save Graph</span>
      </div>

      <%= hidden_field_tag :blank, params[:blank] %>
    <% end %>
  </div>
  
  <div class="clearfix"></div>
  
  <div id="ngramContainer"></div>

  <div id="articleSummaries"></div>
</div>

app/views/articles/wordclouds.html.erb
<div class="span12">
  <div class="page-header">
    <h1>
      <a href="/" class="logo"><%= name_of_site %></a><br>
    </h1>
  </div>

  <div class="span7 cloudsSummary">
    <a href="/" class="homeNav">Home</a>
    
    <h3>Word Clouds by Decade!</h3>
    
    <p>Each cloud is based on the phrases that were most popular in <i>New York Times</i> wedding announcements from that particular decade relative to the other decades</p>
  </div>
  
  <div class="clearfix"></div>
  
  <div class="cloudSocialLinks">
    <span id="tweetButton"></span>
    <!-- <div class="fb-like" data-href="http://www.weddingcrunchers.com" data-width="90" data-layout="button_count" data-show-faces="false" data-send="false"></div> -->
  </div>
  
  <% Article.wordcloud_urls.each do |url| %>
    <div class="wordcloud">
      <%= link_to(image_tag(url), url, :target => "_blank") %>
    </div>
  <% end %>
</div>